CAR_MODELS = {
    'Audi': ['A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'Q3', 'Q5', 'Q7', 'Q8', 'e-tron'],
    'BMW': ['1 Series', '2 Series', '3 Series', '4 Series', '5 Series', '7 Series', 'X1', 'X3', 'X5', 'X6', 'M3', 'M5'],
    'Chevrolet': ['Aveo', 'Bolt', 'Camaro', 'Captiva', 'Cruze', 'Lacetti', 'Malibu', 'Niva', 'Tahoe', 'Trax'],
    'Ford': ['Fiesta', 'Focus', 'Fusion', 'Kuga', 'Mondeo', 'Mustang', 'Ranger', 'Transit'],
    'Honda': ['Accord', 'Civic', 'CR-V', 'HR-V', 'Jazz', 'Pilot'],
    'Hyundai': ['Accent', 'Elantra', 'i30', 'Ioniq 5', 'Kona', 'Santa Fe', 'Sonata', 'Tucson'],
    'Kia': ['Ceed', 'Cerato', 'Niro', 'Optima', 'Rio', 'Sorento', 'Sportage', 'Stinger'],
    'Mazda': ['2', '3', '6', 'CX-3', 'CX-5', 'CX-7', 'CX-9', 'MX-5'],
    'Mercedes-Benz': ['A-Class', 'C-Class', 'E-Class', 'S-Class', 'CLA', 'CLS', 'GLA', 'GLC', 'GLE', 'GLS', 'Sprinter'],
    'Mitsubishi': ['ASX', 'Eclipse Cross', 'L200', 'Lancer', 'Outlander', 'Pajero'],
    'Nissan': ['Ariya', 'Juke', 'Leaf', 'Micra', 'Murano', 'Qashqai', 'Rogue', 'X-Trail'],
    'Opel': ['Astra', 'Combo', 'Corsa', 'Insignia', 'Meriva', 'Mokka', 'Vectra', 'Zafira'],
    'Peugeot': ['2008', '206', '207', '208', '3008', '307', '308', '5008', 'Partner'],
    'Renault': ['Arkana', 'Clio', 'Duster', 'Kadjar', 'Kangoo', 'Logan', 'Megane', 'Scenic'],
    'Skoda': ['Fabia', 'Karoq', 'Kodiaq', 'Octavia', 'Rapid', 'Scala', 'Superb', 'Yeti'],
    'Tesla': ['Model 3', 'Model S', 'Model X', 'Model Y'],
    'Toyota': ['Auris', 'Camry', 'Corolla', 'Highlander', 'Land Cruiser', 'Prius', 'RAV4', 'Yaris'],
    'Volkswagen': ['Arteon', 'Caddy', 'Golf', 'Golf 8', 'Jetta', 'Passat', 'Polo', 'Tiguan', 'Touareg', 'Transporter'],
}
