# Generated by Django 6.0.6 on 2026-06-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('price_usd', models.PositiveIntegerField()),
                ('price_uah', models.PositiveIntegerField()),
                ('mileage', models.PositiveIntegerField()),
                ('transmission', models.CharField(choices=[('A', 'Automatic'), ('M', 'Manual')], max_length=1)),
                ('engine', models.CharField(max_length=50)),
                ('city', models.CharField(default='Unknown', max_length=100)),
                ('plate', models.CharField(max_length=20)),
                ('posted', models.CharField(max_length=50)),
                ('image', models.URLField()),
            ],
        ),
    ]
