# Generated by Django 6.0.6 on 2026-06-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoria', '0004_car_owner_carimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=50, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(max_length=50, verbose_name='Двигун'),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.PositiveIntegerField(verbose_name='Пробіг, тис. км'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=50, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='plate',
            field=models.CharField(max_length=20, verbose_name='Номерний знак'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_uah',
            field=models.PositiveIntegerField(verbose_name='Ціна, грн'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_usd',
            field=models.PositiveIntegerField(verbose_name='Ціна, $'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(verbose_name='Рік'),
        ),
    ]
